version: '3'
services:
  cbook_website:
    container_name: cbook_web
    image: node:latest
    volumes:
      - ./chirpbook-web:/main
    working_dir: /main
    expose:
      - "80"
    environment:
      NODE_ENV: development
    depends_on:
      - cbook_api
    entrypoint: /main/start.sh
    command: [ "install", "prune", "dedupe", "start"]

  cbook_admin:
    container_name: cbook_admin
    image: dpage/pgadmin4
    ports:
      - 9090:80
    volumes:
      - ./database/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD : password
    depends_on:
      - cbook_database

  cbook_api:
    container_name: cbook_api
    image: node:latest
    volumes:
      - ./chirpbook-api:/main
    working_dir: /main
    expose:
      - "8080"
    environment:
      DB_USER: postgres
      DB_HOST: cbook_database
      DB_PORT: 5432
      DB: cbook
      DB_PW: password
      NODE_ENV: development
    depends_on:
      - cbook_database
    entrypoint:
      - /main/start.sh
    command: [ "install", "prune", "dedupe", "start"]

  cbook_database:
    container_name: cbook_database
    image: postgres:latest
    volumes:
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
      # - ./database/postgresql_db_persistent:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cbook
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : password

  cbook_proxy:
    container_name: cbook_proxy
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/development.conf:/etc/nginx/conf.d/default.conf
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - cbook_website
      - cbook_api
    restart: unless-stopped
